"""Highway route shields: accurate placard signs for the compositor.

A route's shield is, in order of preference:

1. **AI sprite** -- a blank shield generated by the asset studio in the map's
   painted style, using a Wikimedia "blank shield" image as the visual
   reference (see ``fetch_shield_reference``). The compositor loads the matted
   sprite and draws the route number on top. This is the primary path.
2. **Procedural** -- an accurate MUTCD-style shape drawn in code (Interstate
   pentagon, US/state circle) when no sprite exists (stub mode, an asset that
   failed, or a network with no reference).
3. **Text badge** -- a neutral rounded rectangle for routes we cannot classify.

The route number is ALWAYS drawn by code (the image model never draws text),
in a clean bold sans for legibility regardless of the map's label font.
"""

from __future__ import annotations

import json
import logging
import re
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from PIL import Image, ImageDraw, ImageFont

from .text import load_font

logger = logging.getLogger(__name__)

# --- classification ---------------------------------------------------------

# Ref-prefix fallbacks, used only when the OSM ``network`` tag is absent.
_INTERSTATE_RE = re.compile(r"^I[- ]?(\d+)$|^Interstate\s+(\d+)$", re.IGNORECASE)
_US_RE = re.compile(r"^US[- ]?(\d+)$|^U\.?S\.?\s*Route\s+(\d+)$", re.IGNORECASE)
_STATE_RE = re.compile(r"^(?:SR|State Route|Loop|L|[A-Z]{2})[- ]?(\d+)$", re.IGNORECASE)
_DIGITS_RE = re.compile(r"(\d+)")

# Two-letter state/territory code -> full name, for resolving the Commons
# "<State> blank.svg" reference file.
STATE_NAMES: dict[str, str] = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas",
    "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware",
    "FL": "Florida", "GA": "Georgia", "HI": "Hawaii", "ID": "Idaho",
    "IL": "Illinois", "IN": "Indiana", "IA": "Iowa", "KS": "Kansas",
    "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MD": "Maryland",
    "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi",
    "MO": "Missouri", "MT": "Montana", "NE": "Nebraska", "NV": "Nevada",
    "NH": "New Hampshire", "NJ": "New Jersey", "NM": "New Mexico", "NY": "New York",
    "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio", "OK": "Oklahoma",
    "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina",
    "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah",
    "VT": "Vermont", "VA": "Virginia", "WA": "Washington", "WV": "West Virginia",
    "WI": "Wisconsin", "WY": "Wyoming", "DC": "District of Columbia",
}


@dataclass(frozen=True)
class ShieldClass:
    """The classified identity of a route shield."""

    kind: str  # "interstate" | "us" | "state" | "generic"
    number: str  # route number, e.g. "10"; "" if none could be parsed
    state: Optional[str] = None  # two-letter state for kind == "state", e.g. "AZ"
    text: str = ""  # full display text for the generic fallback badge


def _clean_ref(ref: Optional[str]) -> str:
    """Reduce an OSM ref to a single primary designation: first of a
    ``;``-joined list, no "Future" qualifier, first two tokens."""
    if not ref:
        return ""
    raw = str(ref).split(";")[0].replace("Future ", "").strip()
    return " ".join(raw.split()[:2])


def classify_shield(ref: Optional[str], network: Optional[str] = None) -> ShieldClass:
    """Classify a route into a shield kind, preferring the OSM ``network`` tag.

    ``network`` values look like ``US:I`` (Interstate), ``US:US`` (US route),
    ``US:AZ`` / ``US:AZ:Loop`` (state route). When absent we fall back to
    matching the ref string prefix.
    """
    cleaned = _clean_ref(ref)
    num_match = _DIGITS_RE.search(cleaned)
    number = num_match.group(1) if num_match else ""

    if network:
        parts = [p for p in str(network).split(":") if p]
        if len(parts) >= 2 and parts[0].upper() == "US":
            sub = parts[1].upper()
            if sub == "I":
                return ShieldClass("interstate", number, text=cleaned)
            if sub == "US":
                return ShieldClass("us", number, text=cleaned)
            return ShieldClass("state", number, state=sub, text=cleaned)

    m = _INTERSTATE_RE.match(cleaned)
    if m:
        return ShieldClass("interstate", m.group(1) or m.group(2), text=cleaned)
    m = _US_RE.match(cleaned)
    if m:
        return ShieldClass("us", m.group(1) or m.group(2), text=cleaned)
    m = _STATE_RE.match(cleaned)
    if m:
        state = cleaned[:2].upper() if cleaned[:2].isalpha() else None
        return ShieldClass("state", m.group(1), state=state, text=cleaned)

    return ShieldClass("generic", number, text=cleaned)


# --- asset identity ---------------------------------------------------------


def shield_network_slug(network: str) -> str:
    """Filesystem/asset-id-safe slug for a network, e.g. "US:AZ" -> "us-az"."""
    return re.sub(r"[^a-z0-9]+", "-", str(network).lower()).strip("-") or "x"


def shield_asset_id(network: str) -> str:
    """Asset id for a network's generated shield sprite."""
    return f"shield_{shield_network_slug(network)}"


# --- Wikimedia reference resolution -----------------------------------------

REFS_DIR = Path(__file__).parent / "shields" / "refs"
_COMMONS_API = "https://commons.wikimedia.org/w/api.php"
_USER_AGENT = "illustrated-maps/0.1 (highway shield reference; https://github.com/nickontiveros/illustrated-maps)"


def reference_title(network: Optional[str]) -> Optional[str]:
    """The Wikimedia Commons "File:..." title of a network's blank shield.

    Returns None for networks we don't have a naming rule for (they fall back
    to a procedurally drawn shield)."""
    if not network:
        return None
    parts = [p for p in str(network).split(":") if p]
    if len(parts) < 2 or parts[0].upper() != "US":
        return None
    sub = parts[1].upper()
    if sub == "I":
        return "File:I-blank.svg"
    if sub == "US":
        return "File:US blank.svg"
    name = STATE_NAMES.get(sub)
    return f"File:{name} blank.svg" if name else None


def cached_shield_reference(network: str, refs_dir: Path = REFS_DIR) -> Optional[Path]:
    """Return the cached reference image path for a network, or None. Never
    touches the network -- safe for offline use (tests, the plan builder)."""
    if reference_title(network) is None:
        return None
    path = refs_dir / f"{shield_network_slug(network)}.png"
    return path if path.exists() else None


def fetch_shield_reference(
    network: str, refs_dir: Path = REFS_DIR, width: int = 512, timeout: float = 12.0
) -> Optional[Path]:
    """Resolve a network's blank-shield reference, fetching it from Wikimedia
    Commons (server-side SVG->PNG render) and caching it under ``refs_dir`` if
    not already present. Best-effort: returns None on any failure so callers
    degrade to a procedural shield."""
    title = reference_title(network)
    if title is None:
        return None
    cached = cached_shield_reference(network, refs_dir)
    if cached is not None:
        return cached
    try:
        params = {
            "action": "query", "format": "json", "prop": "imageinfo",
            "iiprop": "url", "iiurlwidth": str(width), "titles": title,
        }
        api_url = f"{_COMMONS_API}?{urllib.parse.urlencode(params)}"
        req = urllib.request.Request(api_url, headers={"User-Agent": _USER_AGENT})
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = json.load(resp)
        page = next(iter(data["query"]["pages"].values()))
        thumb_url = page["imageinfo"][0]["thumburl"]
        img_req = urllib.request.Request(thumb_url, headers={"User-Agent": _USER_AGENT})
        with urllib.request.urlopen(img_req, timeout=timeout) as resp:
            raw = resp.read()
    except Exception as exc:  # noqa: BLE001 - network/parse failures must not abort planning
        logger.warning("Could not fetch shield reference for %s (%s); using procedural fallback", network, exc)
        return None
    refs_dir.mkdir(parents=True, exist_ok=True)
    path = refs_dir / f"{shield_network_slug(network)}.png"
    path.write_bytes(raw)
    return path


# --- shield number font + overlay -------------------------------------------

_SHIELD_FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
    "C:/Windows/Fonts/arialbd.ttf",
]


def _shield_font(size: int, font_path: Optional[str]) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    """A clean, bold, legible font for the route number. Real placards use a
    crisp sans, so prefer one; only fall back to the map font if none exist."""
    for candidate in _SHIELD_FONT_CANDIDATES:
        if Path(candidate).exists():
            try:
                return ImageFont.truetype(candidate, size)
            except OSError:
                continue
    return load_font(size, font_path, bold=True)


def _number_color(cls: ShieldClass) -> tuple[int, int, int]:
    return (255, 255, 255) if cls.kind == "interstate" else (20, 20, 20)


def _vbias(cls: ShieldClass) -> float:
    """Vertical center of the number as a fraction of height. Interstate
    numbers sit below the red top bar; everything else centers."""
    return 0.60 if cls.kind == "interstate" else 0.5


def _draw_number(img: Image.Image, text: str, fill: tuple[int, int, int], font, vbias: float = 0.5) -> None:
    if not text:
        return
    draw = ImageDraw.Draw(img)
    cx, cy = img.width / 2, img.height * vbias
    try:
        draw.text((cx, cy), text, fill=fill + (255,), font=font, anchor="mm")
    except (TypeError, ValueError):  # very old Pillow without anchor support
        bbox = draw.textbbox((0, 0), text, font=font)
        draw.text((cx - (bbox[2] - bbox[0]) / 2, cy - (bbox[3] - bbox[1]) / 2 - bbox[1]),
                  text, fill=fill + (255,), font=font)


def compose_ai_shield(
    sprite: Image.Image,
    ref: str,
    network: Optional[str],
    size: int,
    font_path: Optional[str] = None,
) -> Image.Image:
    """Scale a studio-generated blank shield sprite to the label size and draw
    the route number on it (code-drawn text on AI art)."""
    cls = classify_shield(ref, network)
    height = max(8, int(size * 1.5))
    width = max(8, int(height * sprite.width / max(1, sprite.height)))
    out = sprite.convert("RGBA").resize((width, height), Image.Resampling.LANCZOS)
    font = _shield_font(int(height * 0.42), font_path)
    _draw_number(out, cls.number, _number_color(cls), font, _vbias(cls))
    return out


# --- procedural tier --------------------------------------------------------


def _render_interstate(number: str, size: int, font_path: Optional[str]) -> Image.Image:
    h = max(8, int(size * 1.5))
    w = max(h, int(h * (0.78 + 0.16 * max(0, len(number) - 2))))
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    blue, red, white = (0, 57, 136), (175, 30, 45), (255, 255, 255)
    m = w * 0.08
    shield = [
        (m, h * 0.15), (w - m, h * 0.15), (w - m, h * 0.62),
        (w / 2, h * 0.92), (m, h * 0.62),
    ]
    draw.polygon(shield, fill=blue, outline=white)
    draw.polygon([(m, h * 0.15), (w - m, h * 0.15), (w - m, h * 0.34), (m, h * 0.34)], fill=red)
    draw.line([(m, h * 0.34), (w - m, h * 0.34)], fill=white, width=max(1, h // 24))
    font = _shield_font(int(h * 0.36), font_path)
    _draw_number(img, number, white, font, 0.62)
    return img


def _render_circle(number: str, size: int, font_path: Optional[str], *,
                   fill: tuple[int, int, int], text: tuple[int, int, int],
                   border: tuple[int, int, int]) -> Image.Image:
    h = max(8, int(size * 1.5))
    w = max(h, int(h * (0.95 + 0.18 * max(0, len(number) - 2))))
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    pad = max(2, int(h * 0.06))
    border_w = max(2, h // 16)
    draw.ellipse([pad, pad, w - pad, h - pad], fill=fill, outline=border, width=border_w)
    font = _shield_font(int(h * 0.4), font_path)
    _draw_number(img, number, text, font, 0.5)
    return img


def _render_us(number: str, size: int, font_path: Optional[str]) -> Image.Image:
    return _render_circle(number, size, font_path,
                          fill=(255, 255, 255), text=(20, 20, 20), border=(20, 20, 20))


def _render_state(number: str, size: int, font_path: Optional[str]) -> Image.Image:
    return _render_circle(number, size, font_path,
                          fill=(255, 255, 255), text=(120, 32, 32), border=(120, 32, 32))


# --- text-badge tier --------------------------------------------------------


def _render_text_badge(text: str, size: int, font_path: Optional[str]) -> Image.Image:
    font = _shield_font(int(size * 1.05), font_path)
    tmp = ImageDraw.Draw(Image.new("RGBA", (1, 1)))
    try:
        bbox = tmp.textbbox((0, 0), text or "?", font=font)
        text_w, text_h = bbox[2] - bbox[0], bbox[3] - bbox[1]
    except Exception:  # noqa: BLE001 - defensive for bitmap fonts
        text_w, text_h = len(text or "?") * size * 0.6, size * 1.3
    pad = size * 0.45
    w = max(8, int(text_w + pad * 2))
    h = max(8, int(text_h + pad))
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    bg, fg, border = (248, 245, 238), (35, 35, 35), (90, 70, 45)
    draw.rounded_rectangle(
        [1, 1, w - 1, h - 1], radius=max(2, int(size * 0.22)),
        fill=bg + (255,), outline=border + (255,), width=max(2, int(size * 0.1)),
    )
    _draw_number(img, text or "?", fg, font, 0.5)
    return img


# --- public fallback entry point --------------------------------------------


def render_shield(
    ref: str,
    network: Optional[str] = None,
    size: int = 24,
    font_path: Optional[str] = None,
) -> Image.Image:
    """Render a shield WITHOUT a generated sprite: an accurate procedural shape
    when the route classifies, else a text badge. The compositor calls this
    only when no AI sprite asset is available. Never raises."""
    cls = classify_shield(ref, network)
    if cls.kind == "interstate" and cls.number:
        return _render_interstate(cls.number, size, font_path)
    if cls.kind == "us" and cls.number:
        return _render_us(cls.number, size, font_path)
    if cls.kind == "state" and cls.number:
        return _render_state(cls.number, size, font_path)
    return _render_text_badge(cls.text or ref, size, font_path)
