name: AZ
region:
  north: 35.75
  south: 32.05
  east: -109.55
  west: -112.45
output:
  width: 7016
  height: 9933
  dpi: 300
style:
  perspective_angle: 35.264
  orientation: north
  orientation_degrees: 340.0
  prompt: Transform this map into a hand illustrated tourist map style. Hand-painted
    illustration aesthetic with warm, muted colors. Aerial view perspective. Maintain
    exact layout of roads, buildings, and features. Clean edges suitable for tiling.
    Desert landscape with warm sand tones and rugged mountain silhouettes.
  color_palette: null
tiles:
  size: 2048
  overlap: 256
sectional_layout:
  focus_regions:
    - name: Phoenix Metro
      bbox:
        north: 33.65
        south: 33.30
        east: -111.80
        west: -112.30
      detail_level: simplified
      scale_factor: 2.5
      landmark_names:
        - Arizona State University
        - Heard Museum
        - Phoenix Art Museum
        - Papago Park
        - Desert Botanical Garden
        - Phoenix Zoo
        - Phoenix Sky Harbor Airport
        - Children's Museum of Phoenix
        - Arizona Science Center
        - Salt River
        - State Farm Stadium
        - Camelback Mountain
      prompt_override: null
    - name: Tucson
      bbox:
        north: 32.35
        south: 32.10
        east: -110.80
        west: -111.10
      detail_level: simplified
      scale_factor: 1.5
      landmark_names:
        - University of Arizona
        - Biosphere 2
      prompt_override: null
    - name: Flagstaff-Sedona
      bbox:
        north: 35.25
        south: 34.75
        east: -111.55
        west: -111.80
      detail_level: simplified
      scale_factor: 1.2
      landmark_names: []
      prompt_override: Transform this map into a hand illustrated tourist map. Red
        rock formations with pine forests. Warm earth tones and dramatic canyon landscape.
    - name: Petrified Forest
      bbox:
        north: 35.10
        south: 34.80
        east: -109.70
        west: -109.95
      detail_level: simplified
      scale_factor: 1.0
      landmark_names:
        - Petrified Forest National Park
      prompt_override: null
  fill_regions:
    - name: Phoenix-Tucson Corridor
      bbox:
        north: 33.30
        south: 32.35
        east: -110.80
        west: -112.30
      detail_level: country
      include_highways: true
      include_rivers: true
      include_terrain_shading: true
      use_ai_illustration: false
      prompt_override: null
    - name: Northern Desert
      bbox:
        north: 35.75
        south: 33.65
        east: -109.55
        west: -112.45
      detail_level: country
      include_highways: true
      include_rivers: true
      include_terrain_shading: true
      use_ai_illustration: false
      prompt_override: null
    - name: Eastern Desert
      bbox:
        north: 34.80
        south: 32.05
        east: -109.55
        west: -110.80
      detail_level: country
      include_highways: true
      include_rivers: true
      include_terrain_shading: true
      use_ai_illustration: false
      prompt_override: null
  coordinate_mapping:
    lat_control_points:
      - - 32.05
        - 0.0
      - - 32.35
        - 0.08
      - - 33.30
        - 0.15
      - - 33.40
        - 0.30
      - - 33.55
        - 0.65
      - - 33.65
        - 0.72
      - - 34.50
        - 0.78
      - - 35.00
        - 0.85
      - - 35.75
        - 1.0
    lon_control_points:
      - - -112.45
        - 0.0
      - - -112.30
        - 0.05
      - - -112.07
        - 0.20
      - - -111.93
        - 0.55
      - - -111.80
        - 0.65
      - - -111.40
        - 0.72
      - - -110.85
        - 0.80
      - - -109.55
        - 1.0
landmarks:
  - name: Wupatki National Monument
    latitude: 35.5574
    longitude: -111.3957
    photo: landmarks/wupatki.jpg
    logo: null
    scale: 2.0
    z_index: 10
    rotation: 0
    feature_type: monument
    elevation_meters: null
    horizon_feature: false
  - name: Arizona State University
    latitude: 33.4242
    longitude: -111.9281
    photo: landmarks/asu.jpg
    logo: logos/asu.png
    scale: 2.0
    z_index: 10
    rotation: 0
    feature_type: campus
  - name: Petrified Forest National Park
    latitude: 34.9839
    longitude: -109.7878
    photo: landmarks/petrified_forest.jpg
    logo: null
    scale: 2.0
    z_index: 10
    rotation: 0
    feature_type: park
  - name: Heard Museum
    latitude: 33.4724
    longitude: -112.0722
    photo: landmarks/heard_museum.jpg
    logo: null
    scale: 1.8
    z_index: 10
    rotation: 0
    feature_type: building
  - name: Phoenix Art Museum
    latitude: 33.4672
    longitude: -112.0739
    photo: landmarks/phoenix_art_museum.jpg
    logo: null
    scale: 1.8
    z_index: 10
    rotation: 0
    feature_type: building
  - name: Papago Park
    latitude: 33.4538
    longitude: -111.9453
    photo: landmarks/papago_park.jpg
    logo: null
    scale: 2.0
    z_index: 8
    rotation: 0
    feature_type: park
  - name: Desert Botanical Garden
    latitude: 33.4600
    longitude: -111.9448
    photo: landmarks/desert_botanical_garden.jpg
    logo: null
    scale: 1.8
    z_index: 10
    rotation: 0
    feature_type: park
  - name: Phoenix Zoo
    latitude: 33.4513
    longitude: -111.9480
    photo: landmarks/phoenix_zoo.jpg
    logo: null
    scale: 1.8
    z_index: 10
    rotation: 0
    feature_type: building
  - name: Phoenix Sky Harbor Airport
    latitude: 33.4352
    longitude: -112.0102
    photo: landmarks/sky_harbor.jpg
    logo: null
    scale: 2.5
    z_index: 5
    rotation: 0
    feature_type: airport
  - name: Children's Museum of Phoenix
    latitude: 33.4507
    longitude: -112.0653
    photo: landmarks/childrens_museum.jpg
    logo: null
    scale: 1.5
    z_index: 10
    rotation: 0
    feature_type: building
  - name: Arizona Science Center
    latitude: 33.4486
    longitude: -112.0666
    photo: landmarks/arizona_science_center.jpg
    logo: null
    scale: 1.8
    z_index: 10
    rotation: 0
    feature_type: building
  - name: Salt River
    latitude: 33.4310
    longitude: -111.9280
    photo: landmarks/salt_river.jpg
    logo: null
    scale: 2.0
    z_index: 3
    rotation: 0
    feature_type: river
    path_coordinates:
      - - 33.5637
        - -111.3862
      - - 33.5300
        - -111.4500
      - - 33.4700
        - -111.6500
      - - 33.4500
        - -111.8200
      - - 33.4310
        - -111.9280
      - - 33.4200
        - -112.0100
      - - 33.3900
        - -112.1800
  - name: State Farm Stadium
    latitude: 33.5273
    longitude: -112.2633
    photo: landmarks/state_farm_stadium.jpg
    logo: null
    scale: 2.5
    z_index: 10
    rotation: 0
    feature_type: stadium
  - name: Camelback Mountain
    latitude: 33.5145
    longitude: -111.9618
    photo: landmarks/camelback_mountain.jpg
    logo: null
    scale: 2.5
    z_index: 8
    rotation: 0
    feature_type: mountain
    elevation_meters: 825.0
    horizon_feature: true
  - name: Biosphere 2
    latitude: 32.5739
    longitude: -110.8504
    photo: landmarks/biosphere_2.jpg
    logo: null
    scale: 2.0
    z_index: 10
    rotation: 0
    feature_type: building
  - name: University of Arizona
    latitude: 32.2317
    longitude: -110.9501
    photo: landmarks/university_of_arizona.jpg
    logo: logos/uofa.png
    scale: 2.0
    z_index: 10
    rotation: 0
    feature_type: campus
